name = "feedback-demo"
pages_build_output_dir = "./dist"

compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "NUXT_DB"
database_name = "feedback-demo"
database_id = "95200c41-c2dd-40dc-811a-86e684640555"
migrations_dir = "./server/utils/db/migrations"
